#!/usr/bin/env python3

import argparse
import subprocess
from pathlib import Path
from typing import Union

import call_wrapper

PathLike = Union[str, Path]

def generate_header_custom( root_dir: PathLike,
                            output_dir: PathLike,
                            component_prefix: str,
                            commit_hash: str = ""):
    if (not commit_hash):
        commit_hash = subprocess.check_output("git rev-parse --short HEAD", shell=True, cwd=root_dir).decode('ascii').strip()

    output_dir = Path(output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir/'commit_hash.h'
    output_file.unlink(missing_ok=True)

    with open(output_file, 'w') as output:
        output.write("// " + f"Generated by '{Path(__file__).name}'\n")
        output.write("#pragma once\n\n")
        output.write(f"#define {component_prefix}_COMMIT_HASH {commit_hash}\n")

    print(f"Generated file: {output_file}")

if __name__ == '__main__':
    cur_dir = Path(__file__).parent.absolute()
    root_dir = cur_dir.parent
    output_dir = root_dir/"_result"/"AllPlatforms"/"generated"

    parser = argparse.ArgumentParser(description='Generate header with commit hash definition')
    parser.add_argument('--output_dir', default=output_dir)
    parser.add_argument('--component_prefix')
    parser.add_argument('--commit_hash', default="")

    args = parser.parse_args()

    call_wrapper.final_call_decorator(
        "Generating header with commit hash",
        "Header was successfully generated!",
        "Header generation failed!"
    )(
    generate_header_custom
    )(
        root_dir,
        args.output_dir,
        args.component_prefix,
        args.commit_hash
    )
